[package]
name = "zege"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.3.1"
sqlx = { version = "0.7.4", features = ["sqlite", "postgres", "runtime-tokio-native-tls", "chrono"] }
tokio = { version = "1.37.0", features = ["full"] } 
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
axum = "0.6"
tower-http = { version = "0.4", features = ["cors"] }
dotenv = "0.15"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v7", "fast-rng"] }
redis = { version = "0.24", features = ["aio", "tokio-comp"] }
anyhow = "1.0.100"
bcrypt = "0.17.1"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }
clap = { version = "4", features = ["derive"] }
config = "0.15.19"

